"限界Times" の正式対応
approvers/MessageQuote pull request #15
Opened 2021-11-03 06:07 UTC by merunno

- RTシステムの追加
- 引用機能の一部処理の高速化

2021-11-03 06:26 UTC, MikuroXina requested changes

2021-11-03 06:26 UTC, MikuroXina commented on lib/context/index.js
> +if (guild === null) {
存在しなかったら `undefined` になるはずなのでこれは危険

2021-11-03 06:26 UTC, MikuroXina commented on lib/context/index.js
> +  throw new Error("環境変数を指定していません。");
エラーメッセージをもう少し親切に, 何の環境変数を指定できていないのかを書くべき

2021-11-03 06:26 UTC, MikuroXina commented on lib/index.js
> +if ([client, guild, TOKEN].includes(null)) {
`null` との比較だけだと `undefined` の場合に対応できない

2021-11-03 06:26 UTC, MikuroXina commented on lib/index.js
> +const TOKEN = process.env["TOKEN"];
定数を `SHOUT_CASE` にするのか `camelCase` にするのか統一すべき

2021-11-03 06:26 UTC, MikuroXina commented on src/run/gtimes/_rt.ts
> +import Discord from "discord.js";
```suggestion
import {Client, MessageEmbed} from "discord.js";
```
使うものだけ `import` すべき

2021-11-03 06:26 UTC, MikuroXina commented on src/run/gtimes/_rt.ts
> +      const messageID = match[2];
```suggestion
      const [, channelID, messageID] = match;
```
これでよい

2021-11-03 06:26 UTC, MikuroXina commented on src/run/gtimes/_rt.ts
> +      const quoteChannel = client.channels.cache.get(`${channelID}`);
```suggestion
      const quoteChannel = client.channels.cache.get(channelID);
```
最初から `string` のモノをテンプレート文字列のプレースホルダーにかけている箇所が多すぎる

2021-11-03 06:26 UTC, MikuroXina commented on src/run/gtimes/_rt.ts
> +      if ([quoteChannel, quoteChannel].includes(null)) return;
```suggestion
      if ([quoteChannel, quoteChannel].includes(undefined)) return;
```
処理が間違っているのを `@ts-ignore` で握りつぶさないで

2021-11-03 14:00 UTC, merunno commented on lib/context/index.js
> +  throw new Error("環境変数を指定していません。");
これはちょっと難しいのでIssueにして分けます。

2021-11-03 15:22 UTC, merunno commented on lib/context/index.js
> +  throw new Error("環境変数を指定していません。");
https://github.com/approvers/MessageQuote/issues/16

2021-11-03 23:11 UTC, MikuroXina requested changes

2021-11-03 23:11 UTC, MikuroXina commented on src/run/gtimes/_rt.ts
> +      if ([quoteChannel, quoteChannel].includes(undefined)) return;
同じ変数を 2 回配列に入れてるけど, おそらくやりたい処理はこれのはず
```suggestion
      if (match.includes(null)) return;
```

2021-11-03 23:11 UTC, MikuroXina commented on src/run/gtimes/_rt.ts
> +          `${message.author.avatarURL()}`
ここなどもっと不要なテンプレート文字列があります

2021-11-03 23:11 UTC, MikuroXina commented on src/run/gtimes/_rt.ts
> +      const regex = /https:\/\/discord.com\/channels\/\d+\/(\d+)\/(\d+)/;
正規表現のリテラル定数は関数の外に出した方が良い

2021-11-04 04:10 UTC, merunno commented on src/run/gtimes/_rt.ts
> +          `${message.author.avatarURL()}`
ここはあえてやってるので解決とさせてください

2021-11-04 04:55 UTC, MikuroXina requested changes

2021-11-04 04:55 UTC, MikuroXina commented on src/run/gtimes/_rt.ts
> +        .setFooter(`${quoteMessage.createdAt}`)
これは Date の toString になりますが, 日本語を対象としているのに日本時間にならないので混乱させるかもしれません

2021-11-04 04:55 UTC, MikuroXina commented on src/run/gtimes/_rt.ts
> +    if (message.content.startsWith("RT:")) {
if の中身が非常に長いので, 反転して早期 return にすべき

2021-11-04 17:06 UTC, merunno commented on src/run/gtimes/_rt.ts
> +        .setFooter(`${quoteMessage.createdAt}`)
Discord Time Stamp機能で解決

2021-11-04 23:16 UTC, MikuroXina requested changes

2021-11-04 23:16 UTC, MikuroXina commented on src/run/gtimes/_rt.ts
> +    if (!quoteChannel?.isText()) return;
14 行目の処理は 15 行目だけでもカバーできます

2021-11-04 23:17 UTC, MikuroXina commented on src/run/gtimes/_rt.ts
> +      const regex = /https:\/\/discord.com\/channels\/\d+\/(\d+)\/(\d+)/;
これは関数を実行する度に RegExp オブジェクトを構築するとパフォーマンスが低下するからです

2021-11-05 06:21 UTC, MikuroXina commented on src/run/gtimes/_rt.ts
> +      rtEmbed.setImage(`${file}`);
`string[]` を文字列に変換しているのが気になる, デザインの意図がわからない

2021-11-07 01:22 UTC, MikuroXina commented on src/run/gtimes/_rt.ts
> +      rtEmbed.setImage(`${file}`);
discord.js のソースコードまで読みましたが, embed は一つの画像を受け付けないので `setImage` も画像の URL に受け取った文字列をそのまま入れています. この文字列変換は前後に `[` ~ `]` を入れてしまうので動かないのでは

2021-11-07 14:27 UTC, MikuroXina approved these changes
#17 で対応するようなので

2021-11-07 14:27 UTC, merged