refactor: 環境変数の取り出し処理
approvers/MessageQuote pull request #167
Opened 2022-04-25 05:22 UTC by mk-el

- あっちこっちで `process.env` に依存しているのでそれの修正
- 環境変数が空文字だった際の対策を追加

2022-04-25 11:39 UTC, MikuroXina requested changes

2022-04-25 11:39 UTC, MikuroXina commented on src/server/command/helpCommand.ts
>  dotenv.config();
あちこちで `dotenv.config` してしまっているのも `server/index.ts` での一箇所にまとめるべきでしょう.

2022-04-26 02:48 UTC, mk-el commented on src/server/command/helpCommand.ts
>  dotenv.config();
`dotenv.config` はやはり呼び出すところではちゃんとやらないといけないみたい

![image](https://user-images.githubusercontent.com/82575685/165209889-60b9f6b9-a0cb-402f-b713-154efa7d0887.png)

![image](https://user-images.githubusercontent.com/82575685/165209895-9a33e5a0-570a-4a63-8c34-77c3633566fd.png)

2022-04-26 03:00 UTC, MikuroXina commented on src/server/command/helpCommand.ts
>  dotenv.config();
でしたら, envManager では extractEnv を export せずにそこで取り出してオブジェクトになったものを export する方は良いでしょう.
今のままだと環境変数名の変更や読み取り方法の修正がし辛いので

2022-04-28 06:51 UTC, MikuroXina requested changes

2022-04-28 06:51 UTC, MikuroXina commented on src/server/util/envManager.ts
> +  defaluts?: Readonly<Partial<Record<K[number], string>>>
`defaults` かと

2022-04-28 06:52 UTC, MikuroXina commented on src/server/util/envManager.ts
> +  defaluts?: Readonly<Partial<Record<K[number], string>>>
使っていないので丸々消してもいいです

2022-04-28 06:55 UTC, MikuroXina approved these changes

2022-04-28 06:55 UTC, merged