eslint・husky/
approvers/MessageQuote pull request #22
Opened 2021-12-10 17:50 UTC by merunno

2021-12-11 02:23 UTC, MikuroXina requested changes

2021-12-11 02:23 UTC, MikuroXina commented on src/command/help.ts
> +    if (i.commandName === 'help') {
条件を逆にして早期 `return` したほうがよさそう

2021-12-11 02:23 UTC, MikuroXina commented on src/command/help.ts
> +          require('discord.js').version
せっかく冒頭で `import` しているので, そこで `version` も `import` したほうがよいかと

2021-12-11 02:23 UTC, MikuroXina commented on package.json
> +    "fix": "npm run format && npm run lint",
`lint` で修正モードにするのはちょっと不便
```suggestion
    "lint": "eslint",
    "fix": "npm run format && npm run lint -- --fix",
```

2021-12-11 02:23 UTC, MikuroXina commented on src/setup/deploy.ts
> +import * as fs from 'fs'
`readdirSync` しか使っていないのでそこだけ `import` したほうがよいかと

2021-12-11 02:23 UTC, MikuroXina commented on src/setup/deploy.ts
> +  throw new Error('環境変数の指定エラー')
別の `Error` のメッセージは英語なのでどちらかに合わせてほしい

2021-12-11 15:30 UTC, merunno commented
アカン事に気づいたのでクローズします

2021-12-11 17:05 UTC, shun-shobon submitted a review, later dismissed

2021-12-12 01:36 UTC, MikuroXina requested changes

2021-12-12 01:36 UTC, MikuroXina commented on src/command/help.ts
> +            require('discord.js').version
ファイル冒頭で `import` しているので, そこで `version` も `import` したほうがよいかと

2021-12-12 01:36 UTC, MikuroXina commented on src/command/help.ts
> +      if (i.commandName === 'help') {
早期 `return` にしましょう

2021-12-12 05:34 UTC, MikuroXina approved these changes
要改善コードがいくつかありますが, 元からなのでとりあえず

2021-12-12 05:34 UTC, merunno commented
ありがとうございました

2021-12-12 05:34 UTC, merged