コマンド・メンション時にヘルプを送信するように・メッセージデバック機能の追加・各種ドキュメントの追加
approvers/MessageQuote pull request #23
Opened 2021-12-14 10:25 UTC by merunno

2021-12-21 22:54 UTC, MikuroXina requested changes

2021-12-21 22:54 UTC, MikuroXina commented on README.md
> +![img.png](image/addBot.png)
alt テキストは書いておきましょう

2021-12-21 22:54 UTC, MikuroXina commented on README.md
> +[このURL](https://discord.com/api/oauth2/authorize?client_id=889343802433757185&permissions=274877914112&scope=bot%20applications.commands) から導入できます。
この URL は別途 MessageQuote の Bot アカウントを作っている人に対して混乱を招くかもしれません

2021-12-21 22:54 UTC, MikuroXina commented on README.md
> +yarn is GOD!!!!!!!
```suggestion
# yarn is GOD!!!!!!!
```
コメントアウトしておきましょう

2021-12-21 22:54 UTC, MikuroXina commented on README.md
> +$ yarn add
```suggestion
$ yarn
```
`yarn install` を `yarn add` に変えるくらいなら `yarn` だけでいいです

2021-12-21 22:54 UTC, MikuroXina commented on README.md
> +$ yarn start
シェルスクリプトとして書いているなら, `$` は取り除いたほうがよいかと

2021-12-21 22:54 UTC, MikuroXina commented on README.md
> +$ yarn upgrade --latest
利用者側で最新版にアップグレードしてしまうと, リポジトリの lock ファイルに従わずに更新してしまうのでうまく動作しなくなる可能性があります. 取り除いてよいかと

2021-12-22 07:59 UTC, MikuroXina approved these changes

2021-12-22 07:59 UTC, merunno commented
thanks!

2021-12-22 07:59 UTC, merged