引用イベントの再構成
approvers/MessageQuote pull request #55
Opened 2022-02-10 13:37 UTC by merunno

- 引用イベントの再構成を行いました。

2022-02-10 13:49 UTC, merunno commented on src/server/service/quoteEvent.ts
> +  }
これどうすればいいの、、、今までやったこと無いからわからない。。。

2022-02-10 13:55 UTC, MikuroXina commented on src/server/service/quoteEvent.ts
> +  }
例えば以下の処理を,
```ts
function hoge() {
  処理1;
  // ここより下を分けたい
  if (判断) return;
  処理2;
  // ここより上を分けたい
  処理3;
}
```
こういうふうに分ければいいです.
```ts
function fuga(x: ForFuga): 'CONTINUE' | 'BREAK' {
  if (判断) return 'BREAK';
  処理2;
  return 'CONTINUE';
}

function hoge() {
  処理1;
  // ここより下を分けたい
  if (fuga(x) === 'BREAK') return;
  // ここより上を分けたい
  処理3;
}
```

2022-02-11 17:12 UTC, MikuroXina requested changes

2022-02-11 17:12 UTC, MikuroXina commented on src/server/service/quoteEvent.ts
> +    .addField('チャンネル', '<#' + quoteChannelId + '>', true)
こういうものはテンプレート文字列を使うべきかと
```suggestion
    .setAuthor({ name: `${quoteUser.username}(${quoteUser.id})` })
    .addField('チャンネル', `<#${quoteChannelId}>`, true)
```

2022-02-11 17:45 UTC, MikuroXina approved these changes

2022-02-11 17:46 UTC, merged